<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NDI-LAP-109" failures="1" tests="9" name="CartTest.CartProductTest" time="30.000" errors="0" timestamp="04 Feb 2022 06:30:52 GMT" skipped="0">
  <testcase classname="CartTest.CartProductTest" name="function" time="0.047"/>
  <testcase classname="CartTest.CartProductTest" name="Case1_verify_site" time="2.025"/>
  <testcase classname="CartTest.CartProductTest" name="Case2_login" time="9.255"/>
  <testcase classname="CartTest.CartProductTest" name="Case3_Add_item" time="3.102"/>
  <testcase classname="CartTest.CartProductTest" name="Case4_Cart_verify_item" time="3.132"/>
  <testcase classname="CartTest.CartProductTest" name="Case5_fill_form" time="8.283"/>
  <testcase classname="CartTest.CartProductTest" name="Case6_finish" time="2.048"/>
  <testcase classname="CartTest.CartProductTest" name="Case7_Homebtn" time="2.059"/>
  <testcase classname="CartTest.CartProductTest" name="Case8_removed" time="0.049">
    <failure message="expected [No Product] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [No Product] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at Functions.FinalPagefunc.checkitem(FinalPagefunc.java:20)
at CartTest.CartProductTest.Case8_removed(CartProductTest.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Case8_removed -->
</testsuite> <!-- CartTest.CartProductTest -->
